### PR TITLE
Add space after commas and add an option to get css colors in color module level 4 format

### PR DESCRIPTION
**Pull request by jeronimoek**
Hi! In this PR I'm modifying primarily two things: 

- Standard legacy color format (added spaces after the commas)
- Standard current CSS Color Module Level 4 (replaces commas with just spaces, removes the **"a"** appended to color formats, e.g. rgba(...) is now just rgb(...), and the alpha value separator is the **"/"** character)

Documentation about the CSS Color Module Level 4 is here: https://www.w3.org/TR/css-color-4/#color-syntax

The way it would work is as follows:

```js
const legacyColor = new ColorTranslator("#004080c0");
console.log(legacyColor.RGB);       // rgb(0, 64, 128)
console.log(legacyColor.RGBA);      // rgba(0, 64, 128, 0.752941)
console.log(legacyColor.HEX);       // #004080
console.log(legacyColor.HEXA);      // #004080C0
console.log(legacyColor.HSL);       // hsl(210, 100%, 25.098039%)
console.log(legacyColor.HSLA);      // hsla(210, 100%, 25.098039%, 0.752941)
console.log(legacyColor.CMYK);      // cmyk(100%, 50%, 0%, 49.803922%)
console.log(legacyColor.CMYKA);     // cmyk(100%, 50%, 0%, 49.803922%, 0.752941)

const level4Color = new ColorTranslator("#004080c0", undefined, true);
console.log(level4Color.RGB);       // rgb(0 64 128)
console.log(level4Color.RGBA);      // rgb(0 64 128 / 0.752941)
console.log(level4Color.HEX);       // #004080
console.log(level4Color.HEXA);      // #004080C0
console.log(level4Color.HSL);       // hsl(210 100% 25.098039%)
console.log(level4Color.HSLA);      // hsl(210 100% 25.098039% / 0.752941)
console.log(level4Color.CMYK);      // cmyk(100% 50% 0% 49.803922%)
console.log(level4Color.CMYKA);     // cmyk(100% 50% 0% 49.803922% / 0.752941)
```

_**⚠This PR is still missing tests, documentation updates, and more, but I wanted to make sure that you agree with these changes before continuing⚠**_

### CODE REVIEW

**Comment by unikitty37** [comment]
Would it be possible to have the `deg` suffix on the angles? This is required by stylelint-config-standard…

**Comment by jeronimoek** [comment]
@unikitty37 It indeed is possible,  but as far as I can tell, using the "deg" suffix or not is equally as valid (neither of those is legacy according to W3C), so I leave it up to @elchininet to decide

**Comment by unikitty37** [comment]
> @unikitty37 It indeed is possible, but as far as I can tell, using the "deg" suffix or not is equally as valid (neither of those is legacy according to W3C), so I leave it up to @elchininet to decide

As the main reason for my raising [the parent issue](https://github.com/jeronimoek/color-picker-universal/issues/83) is to get the colours generated to satisfy stylelint-config-standard, I'd obviously like it to be either always included or an option. At the very least, editing a colour that already has "deg" in place shouldn't cause it to be removed, so I only have to add it the first time…

**Comment by jeronimoek** [comment]
@unikitty37 I think that the `deg` problem might be an issue of stylelint-config-standard since they state in their README:

>It extends [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) and turns on additional rules to enforce modern conventions found in the [CSS specifications](https://www.w3.org/Style/CSS/current-work).

Where `CSS specifications` refers to the W3C web, and as I read through the W3C documentation, I didn't see a single instance where the unitless hue value is legacy.

This is the rule that throws that error
https://stylelint.io/user-guide/rules/hue-degree-notation

**Comment by unikitty37** [comment]
@jeronimoek I don't think anybody's saying unitless is legacy, as such — but stylelint can be used to enforce consistent usage one way or the other, and it would be better if the decision as to which to use came from the stylelint user, and wasn't being forced by ColorTranslator only supporting one way :)

In particular, if a project decides to use stylelint-config-standard to avoid bikeshedding, not supporting the `deg` unit means developers have to put it back in every time they edit a colour.

**Comment by jeronimoek** [comment]
@unikitty37 I agree, but maybe we should look into that in another issue since the changes presented here are required to allow non-legacy color formats (CSS Colors Module Level 4), meanwhile, the `deg` problem is related to users of stylelint-config-recommended library.
Depending on what @elchininet decides, we either could add the `deg` suffix by default or otherwise, we might need to add another option to tackle that problem, which would require another issue in my opinion

**Comment by elchininet** [comment]
Hi @jeronimoek,

Pull requests are always welcome and you already have contributed to the project :)

CSS Level 4 is something that I have on my list since a long time.

Some comments about this pull request in particular:

1. Avoid refactorings of the code when you want to implement a new feature, this only makes the pull request harder to review. Ship only the minimum required changes to implement the new feature, the rest of the changes could be made in separate pull requests.
2. Avoid making changes that are not fully justified in the pull request description. Adding spaces after the commas is not something necessary by the CSS specification and it is not related to the CSS Level 4 either, so it seems that it is something that you need, want or prefer, but for that you need to provide reasons of the change and preferably make them in a separate pull request.
3. I agree with @unikitty37, it should not be up to the library to decide the format of the final CSS, the user should be able to select it. Now that the intention is to bring CSS Level 4, this is a good oportunity to avoid forcing the final format of the CSS. The library [already accepts CSS Level 4 inputs](https://github.com/elchininet/ColorTranslator#css-string-inputs), it should be able to generate all these formats as the output in the same way.

So, these are my thoughts about how should be the proper way to implement this:

This change can be shipped as a breaking change (a major version of the library), so I think that it should be safe to remove legacy support by default from the output, obtainig the output in the legacy format should be optional (the opposite to what you are trying to achieve). If someone wants the legacy format by default, they can stick to an old version.

At the moment, the static methods require many parameters, this will became a big problem in the future because new options will be requested, so more parameters will be added. If one wants to add a parameter that is at the end of the method one should send `undefined` or set a value in the previous ones, this will become problematic when more parameters are added. This is a good opportunity to introduce a configuration object. Only one parameter could be sent at the end of the static methods or sent to the class instance. All the options of this configuration object should be optional so it is easy to add more and more options in the future and the options should be intended just to override the default ones. This configuration object could have a shape like this one (I didn‘t thought deeply about it, so this is just to give an idea):

```javascript
// config optional parameter
{
    decimals: 2,
    legacy: true,
    anglesUnit: 'deg',
    spacesAfterCommas: true
}
``` 

Now, the library could detect these parameters in the input, so if someone is using a format for the input, the library should return the same format without the necessity of providing a configuration. If one wants different types of input but a consistent output, then a configuration is needed, if a configuration is sent it rules over the input format. This solves what you want to achieve with the commas after the values, what @unikitty37 is searching for his use case and I think that it should be flexible enough for any use case. 

* If one sends `#FF00FF55` => Defaults options
* If one sends `rgb(100,40,12)` => legacy: true / spacesAfterCommas: false
* If one sends `hsl(300deg 100% 50% / 50%)` => legacy: false / anglesUnit: deg

I would like to hear your opinon and also @unikitty37‘s opinion. For this changes we should create a branch prepared for the next big release and ship the changes in small commits intended for specific things as it is easier to review (migrate to a configuration object, detect the options from the input, apply different templates depending on the configuration, etc). I can help to work on it.

Let me both know your thoughts, regards.

**Comment by jeronimoek** [comment]
@elchininet Thanks for your attention! I agree with you. This would make a big improvement to the library. I'll wait for the new branch.
Regarding the library setting the options based on the input value, we should decide how it will work when there is more than one color input involved, for example, when using a color blend or color mix static method.
Also, I'm not so used to this workflow. Should we create a new issue and track the progress there?
Maybe we could use a `task list` for this purpose. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by unikitty37** [comment]
@elchininet I like this — it looks like it should be flexible enough to handle all the use cases I can think of. Thanks!

**Comment by elchininet** [comment]
Ok @jeronimoek,
I‘ll create the issue and the task list soon, but we can sync and change things there once it is done.
Regards

**Comment by elchininet** [comment]
Hi @jeronimoek,
Here you go: https://github.com/elchininet/ColorTranslator/issues/114
We can split the tasks between us, so just let me know if you prefer tp cover only certain tasks and I‘ll take care of the rest.
Regards

**Pull request closed without merging**
